# .github/workflows/go-backend.yml
name: Go Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Cache Go modules & build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          # point at your server/go.sum
          key: ${{ runner.os }}-go-mod-${{ hashFiles('server/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install deps, lint & test
        run: |
          cd server
          # Fetch modules
          go mod download

          # Optional sanity checks
          go fmt ./...
          go vet ./...

          # Run all tests with coverage
          go test ./... -v -coverprofile=coverage.out

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: server/coverage.out
